#!/usr/bin/env bash
set -euo pipefail

# All local model state is kept on the /data/predator/ly volume.
export MEMBIND_DATA_ROOT="${MEMBIND_DATA_ROOT:-/data/predator/ly/Mem}"
export MEMBIND_REPO_ROOT="${MEMBIND_REPO_ROOT:-/data/predator/ly/MemBind}"
export MEMBIND_ENV="${MEMBIND_ENV:-$MEMBIND_DATA_ROOT/envs/membind-local}"
export MEMBIND_MODEL_ROOT="${MEMBIND_MODEL_ROOT:-$MEMBIND_DATA_ROOT/models}"
export MEMBIND_LLM_MODEL_DIR="${MEMBIND_LLM_MODEL_DIR:-$MEMBIND_MODEL_ROOT/Qwen3-14B-AWQ}"
export MEMBIND_EMBED_MODEL_DIR="${MEMBIND_EMBED_MODEL_DIR:-$MEMBIND_MODEL_ROOT/Qwen3-Embedding-0.6B}"
export MEMBIND_LLM_HOST="${MEMBIND_LLM_HOST:-127.0.0.1}"
export MEMBIND_LLM_PORT="${MEMBIND_LLM_PORT:-18100}"
export MEMBIND_EMBED_HOST="${MEMBIND_EMBED_HOST:-127.0.0.1}"
export MEMBIND_EMBED_PORT="${MEMBIND_EMBED_PORT:-18101}"
export MEMBIND_LLM_MODEL_NAME="${MEMBIND_LLM_MODEL_NAME:-qwen3-14b-awq}"
export MEMBIND_EMBED_MODEL_NAME="${MEMBIND_EMBED_MODEL_NAME:-qwen3-embedding-0.6b}"
export MEMBIND_PROFILE_ID="${MEMBIND_PROFILE_ID:-local-qwen3-14b-awq-v1}"
export MEMBIND_PROFILE_ROOT="${MEMBIND_PROFILE_ROOT:-$MEMBIND_DATA_ROOT/profiles}"
export MEMBIND_LOCAL_API_KEY="${MEMBIND_LOCAL_API_KEY:-membind-local}"
export MEMBIND_NEO4J_URI="${MEMBIND_NEO4J_URI:-bolt://127.0.0.1:7687}"

export HF_HOME="${HF_HOME:-$MEMBIND_DATA_ROOT/cache/huggingface}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-$HF_HOME/hub}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$HF_HOME/datasets}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HUB_CACHE}"
export TORCH_HOME="${TORCH_HOME:-$MEMBIND_DATA_ROOT/cache/torch}"
export VLLM_CACHE_ROOT="${VLLM_CACHE_ROOT:-$MEMBIND_DATA_ROOT/cache/vllm}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$MEMBIND_DATA_ROOT/cache}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$MEMBIND_DATA_ROOT/cache/pip}"
export TMPDIR="${TMPDIR:-$MEMBIND_DATA_ROOT/tmp/membind-local}"
export CUDA_CACHE_PATH="${CUDA_CACHE_PATH:-$MEMBIND_DATA_ROOT/cache/cuda}"
export FLASHINFER_WORKSPACE_BASE="${FLASHINFER_WORKSPACE_BASE:-$MEMBIND_DATA_ROOT/cache/flashinfer}"
export VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR="${VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR:-$MEMBIND_DATA_ROOT/cache/flashinfer/autotune}"
export VLLM_USE_FLASHINFER_SAMPLER="${VLLM_USE_FLASHINFER_SAMPLER:-0}"

export MEMBIND_LLM_TMUX_SESSION="${MEMBIND_LLM_TMUX_SESSION:-membind-local-llm}"
export MEMBIND_EMBED_TMUX_SESSION="${MEMBIND_EMBED_TMUX_SESSION:-membind-local-embedding}"

mkdir -p "$MEMBIND_MODEL_ROOT" "$HF_HUB_CACHE" "$TORCH_HOME" "$VLLM_CACHE_ROOT" \
  "$PIP_CACHE_DIR" "$TMPDIR" "$CUDA_CACHE_PATH" "$FLASHINFER_WORKSPACE_BASE" \
  "$VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR" \
  "$MEMBIND_DATA_ROOT/logs/membind-local" "$MEMBIND_DATA_ROOT/run/membind-local" \
  "$MEMBIND_PROFILE_ROOT/$MEMBIND_PROFILE_ID"

export PATH="$MEMBIND_ENV/bin:$PATH"

local_python() {
  "$MEMBIND_ENV/bin/python" "$@"
}

local_hf() {
  if [[ -x "$MEMBIND_ENV/bin/hf" ]]; then
    "$MEMBIND_ENV/bin/hf" "$@"
  else
    "$MEMBIND_ENV/bin/huggingface-cli" "$@"
  fi
}
